### ISSUE TITLE
Union estimate matrix space optimization

### ISSUE THREAD

**Issue by Felix-Droop** [seqan/chopper#49]
Currently, all the union_estimates for `chopper pack` with the `-u` flag are stored in a `vector<vector<uint64_t>>`. The total number of needed entries is n*n / 2 where n is the number of user bins. The matrix would hence consume 4 TB of RAM for around 1,000,000 user bins:
```
n * n | 1<<20 * 1<<20 = 1<<40
  / 2 | 1<<39
  * 8 | 1<<42
```

The matrices of the hierarchical binning itself need much less memory when the number of technical bins is reasonable. The clustering of `chopper pack` with the `-r` flag generally needs even more memory than the union estimates, but we can set the `--max-ratio` parameter (a.k.a. _r_ in my thesis) to something close to 1 to reduce the amount of memory needed. This is achieved by performing multiple smaller clustering runs instead of a single large run.

It follows that the union estimate matrix is likely the memory bottleneck for `chopper pack`. There are a few ideas to mitigate this problem:

- Don't store all union estimates, only the ones that will likely be used (e.g. we usually don't really need to know the cardinality of the union of all user bins and other large intervals of the user bin sequence). This might already be enough for our needs.
- Use smaller data types as entries since we usually don't need the full range of a 64 bit unsigned integer.
- Sophisticated matrix compression techniques from literature.

**Comment by smehringer** [comment]
This was fixed by #100. Instead of computing the full matrix, we only store what is needed to compute a column in the DP matrix. This has implications on the runtime that were not benchmarked but should not be too high as it is not in the hot loop of the DP algorithm.
